# Generated by Django 6.0.4 on 2026-04-13 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('VendorSide', '0005_alter_vendorworks_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField()),
                ('vendor_work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_data', to='VendorSide.vendorworks')),
            ],
        ),
    ]
