# Generated by Django 5.2.13 on 2026-04-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rag_ai', '0002_alter_vendorembedding_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorembedding',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
