# Generated by Django 6.0.2 on 2026-02-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_customuser_certificate_customuser_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='wants_to_be_staff',
            field=models.BooleanField(default=False),
        ),
    ]
