# Generated by Django 6.0 on 2026-02-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
