# Generated by Django 6.0 on 2026-03-02 09:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_customuser_business_name_customuser_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='certificate',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificate'),
        ),
    ]
