# Generated by Django 6.0 on 2026-03-05 10:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_customuser_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='certificate',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
