# Generated by Django 6.0 on 2026-02-25 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verificaton', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
