# Generated by Django 6.0 on 2026-03-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorSide', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vendorworks',
            name='id_available',
            field=models.BooleanField(default=True),
        ),
    ]
