# Generated by Django 6.0 on 2026-03-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VendorSide', '0002_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorworks',
            old_name='id_available',
            new_name='is_available',
        ),
    ]
