# Generated by Django 6.0 on 2026-04-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorSide', '0003_rename_id_available_vendorworks_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorworks',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorworks',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
