# Generated by Django 6.0 on 2026-04-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorSide', '0004_vendorworks_latitude_vendorworks_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorworks',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendorworks',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
